token:
  - <telegram-bot-token>
emby-server:
  - http://<emby-server-url>:<port>
admins:
  - <telegram-chatid-admin-1>
  - <telegram-chatid-admin-1>
users:
  - <telegram-chatid-user-1>
  - <telegram-chatid-user-2>
